
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: build
   jobs:
   - job: FirstJob
     steps:
     - bash: echo Build firstjob
   - job: seconjob
     steps:
     - bash: echo build secondjob

 - stage: dev
   dependsOn: build
   jobs:
    - job: Firstjob
      steps:
      - bash: echo dev firstjob
    - job: secondjob
      steps:
       - bash: echo dev seconjob
 - stage: Qa
   dependsOn: build
   jobs:
      - job: Firstjob
        steps:
        - bash: echo dev firstjob
      - job: secondjob
        steps:
         - bash: echo dev seconjob
 - stage: prod
   dependsOn: Qa
   jobs:
   - job: Firstjob
     steps:
      - bash: echo dev firstjob
   - job: secondjob
     steps:
         - bash: echo dev seconjob

  


